config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [:show, :index, :new, :create, :edit, :update] do
    collection do
      get 'vodka'
      get 'gin'
      get 'rum'
      get 'bourbon'
      get 'scotch'
      get 'whiskey'
      get 'tequila'
      get 'brandy'
      get 'other'
    end
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_one_attached :file
  has_many :doses, dependent: :destroy
  has_many :ingredients, :through => :doses

  validates :name, presence: true, uniqueness: true
  validates :category, presence: true, inclusion: {in: ['Vodka', 'Gin', 'Rum', 'Bourbon', 'Scotch', 'Whiskey', 'Tequila', 'Brandy', 'Other']}
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    @cocktail.save
    redirect_to cocktail_path(@cocktail)
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    @cocktail.update(cocktail_params)
    @cocktail.save
    redirect_to cocktail_path(@cocktail)
  end

  ## collection here

  def vodka
    @cocktails = Cocktail.where(category: 'Vodka')
  end

  def gin
    @cocktails = Cocktail.where(category: 'Gin')
  end

  def rum
    @cocktails = Cocktail.where(category: 'Rum')
  end

  def bourbon
    @cocktails = Cocktail.where(category: 'Bourbon')
  end

  def scotch
    @cocktails = Cocktail.where(category: 'Scotch')
  end

  def whiskey
    @cocktails = Cocktail.where(category: 'Whiskey')
  end

  def tequila
    @cocktails = Cocktail.where(category: 'Tequila')
  end

  def brandy
    @cocktails = Cocktail.where(category: 'Brandy')
  end

  def other
    @cocktails = Cocktail.where(category: 'Other')
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :category, :photo, :file)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def show
    @does = Dose.new(params[:id])
  end

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@dose.cocktail)
    else
      render 'new'
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/bourbon.html.erb
<div class="container">
  <h1>Bourbon Specials</h1>
  <%= link_to 'Add new', new_cocktail_path, class: "btn btn-primary mb-3 rounded" %> | <%= link_to 'Back', cocktails_path, class: "btn btn-warning mb-3 rounded" %>
  <div class="row">
    <% @cocktails.each do |c| %>
      <div class="cocktail-card col-xs-12 col-sm-4 ">
        <%= image_tag c.photo, width: 300, height: 350 %>
        <div class="cocktail-name">
          <h3><%= link_to c.name, c %></h3>
        </div>
      </div>
    <% end %>
  </div>
  <%= link_to 'Back', cocktails_path, class: "btn btn-warning mb-3 rounded" %>
</div>

app/views/cocktails/brandy.html.erb
<div class="container">
  <h1>Brandy Specials</h1>
   <%= link_to 'Add new', new_cocktail_path, class: "btn btn-primary mb-3 rounded" %> | <%= link_to 'Back', cocktails_path, class: "btn btn-warning mb-3 rounded" %>
  <div class="row">
    <% @cocktails.each do |c| %>
      <div class="cocktail-card col-xs-12 col-sm-4 ">
        <%= image_tag c.photo, width: 300, height: 350 %>
        <div class="cocktail-name">
          <h3><%= link_to c.name, c %></h3>
        </div>
      </div>
    <% end %>
  </div>
  <%= link_to 'Back', cocktails_path, class: "btn btn-warning mb-3 rounded" %>
</div>

app/views/cocktails/edit.html.erb
<div class="container">
  <h1>🍹 Give <%= @cocktail.name %> a nice shot! 🍸</h1>
  <div class="form-card">
    <%= simple_form_for(@cocktail) do |f| %>
    <%= f.input :name, disabled: true, hint: "you can't change the name" %>
    <%= f.input :category, disabled: true, hint: "you can't change the category" %>
    <%= f.input :photo, label: 'photo url' %>
    <%= f.button :submit, class: "btn-primary" %>
    <% end %>
  </div>

app/views/cocktails/gin.html.erb
<div class="container">
  <h1>Gin Specials</h1>
  <%= link_to 'Add new', new_cocktail_path, class: "btn btn-primary mb-3 rounded" %> | <%= link_to 'Back', cocktails_path, class: "btn btn-warning mb-3 rounded" %>
  <div class="row">
    <% @cocktails.each do |c| %>
      <div class="cocktail-card col-xs-12 col-sm-4 ">
        <%= image_tag c.photo, width: 300, height: 350 %>
        <div class="cocktail-name">
          <h3><%= link_to c.name, c %></h3>
        </div>
      </div>
    <% end %>
  </div>
  <%= link_to 'Back', cocktails_path, class: "btn btn-warning mb-3 rounded" %>
</div>

app/views/cocktails/index.html.erb
<div class="banner">
  <div class="d-flex justify-content-center align-items-center">
    <div class="banner-text">
      <h1>Welcome to Mister Cocktail</h1>
      <h1>Your personal bartender</h1>
      <%= link_to 'Add new cocktail', new_cocktail_path, class: "btn btn-lg btn-primary" %>
    </div>
  </div>
</div>
<div class="container">
  <div class="container2">
    <h2>Choose by spirit</h2>
    <div class="row">
    <div class="cocktail-card col-xs-12 col-sm-4">
      <img src="https://www.liquor.com/thmb/7bsovOaFAeH0_UZ9h1jZuuq8ZK0=/960x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Gin-and-Tonic-720x720-recipe-1194ca2779ea49b9985cb4af11021aea.jpg" alt="vodka" class="cocktail-card-img">
      <%= link_to 'Vodka', vodka_cocktails_path, class: "btn btn-lg btn-warning" %>
    </div>
    <div class="cocktail-card col-xs-12 col-sm-4">
      <img src="https://www.liquor.com/thmb/5_QL8Z-1aEFv_gJ5JxTwZH7jzfY=/960x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/50-50-Birthday-Martini-Credit-Jena-Ellenwood_main_720x720-8eed55390584432e9f3f0b4727b92a15.jpg" alt="gin" class="cocktail-card-img">
      <%= link_to 'Gin', gin_cocktails_path, class: "btn btn-lg btn-warning" %>
    </div>
    <div class="cocktail-card col-xs-12 col-sm-4">
      <img src="https://www.liquor.com/thmb/KVNiKudsoEikPjqJ8GhHXHJwvs4=/960x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/americano-720x720-article-95bbb8da50dc4de3aff7facca99abca6.jpg" alt="rum" class="cocktail-card-img">
      <%= link_to 'Rum', rum_cocktails_path, class: "btn btn-lg btn-warning" %>
    </div>
    <div class="cocktail-card col-xs-12 col-sm-4">
      <img src="https://www.liquor.com/thmb/nwmtt_ZWA7O0YbTVeTcYf2mRWT4=/960x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Switchel-at-Daisies-photo-credit-Ryan_Gorey_article_720x720-9de37d578ff24d4b9af20c6762351312.jpg" alt="bourbon" class="cocktail-card-img">
      <%= link_to 'Bourbon', bourbon_cocktails_path, class: "btn btn-lg btn-warning" %>
    </div>
    <div class="cocktail-card col-xs-12 col-sm-4">
      <img src="https://www.liquor.com/thmb/G0BRGj8XH6yJAdTerva6jA-wJkc=/960x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/rusty-nail-720x720-recipe-baa8b8fbcf81444ca5906441f51a15c3.jpg" alt="scotch" class="cocktail-card-img">
      <%= link_to 'Scotch', scotch_cocktails_path, class: "btn btn-lg btn-warning" %>
    </div>
    <div class="cocktail-card col-xs-12 col-sm-4">
      <img src="https://www.liquor.com/thmb/NwPjAhfPaP4HxHYB-JLCq_T5xg8=/960x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Thick-as-Thieves-main_720x720-9ae0980d4a9c470db85a82457fa6e103.jpg" alt="whiskey" class="cocktail-card-img">
      <%= link_to 'Whiskey', whiskey_cocktails_path, class: "btn btn-lg btn-warning" %>
    </div>
    <div class="cocktail-card col-xs-12 col-sm-4">
      <img src="https://www.liquor.com/thmb/3BW_r72_OiCEdCSwk3Ez3jQG2vs=/960x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__liquor__2018__08__10151022__margarita-720x720-article-3ef4a1dc383e43f18703f735af00220a.jpg" alt="tequila" class="cocktail-card-img">
      <%= link_to 'Tequila', tequila_cocktails_path, class: "btn btn-lg btn-warning" %>
    </div>
    <div class="cocktail-card col-xs-12 col-sm-4">
      <img src="https://www.liquor.com/thmb/EkRh_Lp1I08vYvX4hdj1fasdZCc=/960x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/bagrationi_article_720x720-94e71b6622384bf7a3913d511394338c.jpg" alt="brandy" class="cocktail-card-img">
      <%= link_to 'Brandy', brandy_cocktails_path, class: "btn btn-lg btn-warning" %>
    </div>
    <div class="cocktail-card col-xs-12 col-sm-4">
      <img src="https://www.liquor.com/thmb/HTYQdDqLp_HUALyJKZmstD-XwII=/960x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__liquor__2019__07__12101312__Blue-Hawaii-720x720-recipe-1c521445b9394786abe8215118baf734.jpg" alt="other" class="cocktail-card-img">
      <%= link_to 'Other', other_cocktails_path, class: "btn btn-lg btn-warning" %>
    </div>
        </div>

  </div>
</div>
<!-- all 9 categories -->

app/views/cocktails/new.html.erb
<div class="container">
  <h1>🍹 One more? YES, please! 🍸</h1>
  <div class="form-card">
    <%= simple_form_for(@cocktail) do |f| %>
    <%= f.error_notification %>
    <%= f.input :name %>
    <%= f.input :category, collection: ['Vodka', 'Gin', 'Rum', 'Bourbon', 'Scotch', 'Whiskey', 'Tequila', 'Brandy', 'Other'] %>
    <%= f.input :photo, label: 'Put photo url here', hint: 'you may find a photo later!' %>
    <%= f.button :submit, class: "btn-primary" %>
    <% end %>
  </div>
</div>

app/views/cocktails/other.html.erb
<div class="container">
  <h1>Many more ...</h1>
   <%= link_to 'Add new', new_cocktail_path, class: "btn btn-primary mb-3 rounded" %> | <%= link_to 'Back', cocktails_path, class: "btn btn-warning mb-3 rounded" %>
  <div class="row">
    <% @cocktails.each do |c| %>
      <div class="cocktail-card col-xs-12 col-sm-4 ">
        <%= image_tag c.photo, width: 300, height: 350 %>
        <div class="cocktail-name">
          <h3><%= link_to c.name, c %></h3>
        </div>
      </div>
    <% end %>
  </div>
  <%= link_to 'Back', cocktails_path, class: "btn btn-warning mb-3 rounded" %>
</div>

app/views/cocktails/rum.html.erb
<div class="container">
  <h1>Rum Specials</h1>
   <%= link_to 'Add new', new_cocktail_path, class: "btn btn-primary mb-3 rounded" %> | <%= link_to 'Back', cocktails_path, class: "btn btn-warning mb-3 rounded" %>
  <div class="row">
    <% @cocktails.each do |c| %>
      <div class="cocktail-card col-xs-12 col-sm-4 ">
        <%= image_tag c.photo, width: 300, height: 350 %>
        <div class="cocktail-name">
          <h3><%= link_to c.name, c %></h3>
        </div>
      </div>
    <% end %>
  </div>
  <%= link_to 'Back', cocktails_path, class: "btn btn-warning mb-3 rounded" %>
</div>

app/views/cocktails/scotch.html.erb
<div class="container">
  <h1>Scotch Specials</h1>
  <%= link_to 'Add new', new_cocktail_path, class: "btn btn-primary mb-3 rounded" %> | <%= link_to 'Back', cocktails_path, class: "btn btn-warning mb-3 rounded" %>
  <div class="row">
    <% @cocktails.each do |c| %>
      <div class="cocktail-card col-xs-12 col-sm-4 ">
        <%= image_tag c.photo, width: 300, height: 350 %>
        <div class="cocktail-name">
          <h3><%= link_to c.name, c %></h3>
        </div>
      </div>
    <% end %>
  </div>
  <%= link_to 'Back', cocktails_path, class: "btn btn-warning mb-3 rounded" %>
</div>

app/views/cocktails/show.html.erb
<div class="container">
  <h1>🍸 Learn more about: <%= @cocktail.name %></h1>
   <div class="cocktail-card-img">
    <% if @cocktail.photo.nil? %>
      <%= link_to 'Add photo', edit_cocktail_path, class: "btn btn-info" %>
    <% else %>
      <%= image_tag @cocktail.photo, width: 500, height: 500%>
    <% end %>
    <h3><%= @cocktail.name%></h3>
    <h4>Catetory: <%= @cocktail.category %></h4>
    <%= link_to 'Edit photo url', edit_cocktail_path, class: "btn btn-success" %> |
    <%= link_to 'Back', cocktails_path, class: "btn btn-primary" %> | <%= link_to 'Add a dose', new_cocktail_dose_path(@cocktail), class: "btn btn-info"  %>
  </div>
  <div class="dose-des">
    <h4>Doses</h4>
      <ul>
      <% @cocktail.doses.each do |dose| %>
      <li><%= dose.description %> | <%= dose.ingredient.name %></li>

      <%= link_to 'Delete dose', dose_path(dose), method: :delete, data: { confirm: 'are you sure??'}, class: "btn btn-danger" %>
      <% end %>
    </ul>
  </div>
</div>

app/views/cocktails/tequila.html.erb
<div class="container">
  <h1>Tequila Specials</h1>
  <%= link_to 'Add new', new_cocktail_path, class: "btn btn-primary mb-3 rounded" %> | <%= link_to 'Back', cocktails_path, class: "btn btn-warning mb-3 rounded" %>
  <div class="row">
    <% @cocktails.each do |c| %>
      <div class="cocktail-card col-xs-12 col-sm-4 ">
        <%= image_tag c.photo, width: 300, height: 350 %>
        <div class="cocktail-name">
          <h3><%= link_to c.name, c %></h3>
        </div>
      </div>
    <% end %>
  </div>
  <%= link_to 'Back', cocktails_path, class: "btn btn-warning mb-3 rounded" %>
</div>

app/views/cocktails/vodka.html.erb
<div class="container">
  <h1>Vokda Specials</h1>
  <%= link_to 'Add new', new_cocktail_path, class: "btn btn-primary mb-3 rounded" %> | <%= link_to 'Back', cocktails_path, class: "btn btn-warning mb-3 rounded" %>
  <div class="row">
    <% @cocktails.each do |c| %>
      <div class="cocktail-card col-xs-12 col-sm-4 ">
        <%= image_tag c.photo, width: 300, height: 350 %>
        <div class="cocktail-name">
          <h3><%= link_to c.name, c %></h3>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/whiskey.html.erb
<div class="container">
  <h1>Whishkey Specials</h1>
   <%= link_to 'Add new', new_cocktail_path, class: "btn btn-primary mb-3 rounded" %> | <%= link_to 'Back', cocktails_path, class: "btn btn-warning mb-3 rounded" %>
  <div class="row">
    <% @cocktails.each do |c| %>
      <div class="cocktail-card col-xs-12 col-sm-4 ">
        <%= image_tag c.photo, width: 300, height: 350 %>
        <div class="cocktail-name">
          <h3><%= link_to c.name, c %></h3>
        </div>
      </div>
    <% end %>
  </div>
  <%= link_to 'Back', cocktails_path, class: "btn btn-warning mb-3 rounded" %>
</div>

app/views/doses/new.html.erb
<div class="container">
  <h4>Add a dose</h4>
  <%= simple_form_for([@cocktail, @dose]) do |f| %>
  <%= f.input :description, hint: '1 indegredient/dose' %>
  <%= f.association :ingredient, collection: Ingredient.all %>
  <%= f.button :submit, class: "btn btn-light" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>